name: rentify
description: rentify

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.0+3

environment:
  sdk: ">=3.5.4 <4.2.0"



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  get: 4.6.6
  flutter_screenutil: 5.9.3
  google_fonts: 6.2.1
  font_awesome_flutter: 10.8.0
  country_code_picker: 3.1.0
  material_design_icons_flutter: 7.0.7296
  get_storage: ^2.0.3
  connectivity_plus: 6.0.5
  logger: 2.4.0
  pin_code_fields: 8.0.1
  intl: 0.19.0
  image_picker: 1.1.2
  flutter_inappwebview: 6.1.5
  dotted_border: ^2.1.0
  flutter_animate: 4.5.0
  dotted_line: 3.2.3
  carousel_slider: 5.0.0
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.17
  material_symbols_icons: 4.2789.0
  flutter_staggered_animations: ^1.1.1
  flutter_spinkit: ^5.2.0
  dart_code_metrics:
  restart_app: ^1.3.2
  # google_maps_flutter: ^2.6.0
  # geocoding: ^2.1.1
  # google_place_plus: ^1.0.0   # lightweight Places autocomplete

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  flutter_launcher_icons:
  change_app_package_name: 1.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app/app_launcher.png"

flutter_gen:
  output: lib/custom_assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter:
  uses-material-design: true
  assets:
    - assets/background/
    - assets/clipart/
    - assets/icon/
    - assets/logo/